services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      APP_ENV: ${APP_ENV}
      MIGRATION_VERSION: ${MIGRATION_VERSION}
      PGDATA: ${PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:${PGDATA}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    build:
      context: .
      dockerfile: docker/migrate/Dockerfile
    restart: "no"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_TEST_DB: ${POSTGRES_TEST_DB}
      MIGRATION_VERSION: ${MIGRATION_VERSION}
    volumes:
      - ./migrations:/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy

  seed:
    image: golang:1.24-alpine
    restart: "no"
    working_dir: /app
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: ["go", "run", "./cmd/seeder"]

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_SOURCE_NAME: "postgresql://${METRICS_USER}:${METRICS_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./docker/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
