version: "2"

linters:
  enable:
    - errorlint
    - govet
    - misspell
    - nakedret
    - nilerr
    - revive
    - unconvert
    - whitespace
  settings:
    misspell:
      locale: US
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - linters:
          - revive
        text: "unexported-return"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/pg-tools/pgcompare